### PR TITLE
Feature-Praise: Authentication-context-provider

### PR DESCRIPTION
**Pull request by AccoladesIO**

### CODE REVIEW

**Review by annonymousauthority — CHANGES_REQUESTED** [review]
Show a video demo of implementation as requested

**Review by annonymousauthority — COMMENTED** [review]
@Remi-dee does this work?

**Comment by Remi-dee** [comment]
> @Remi-dee does this work?

I’ll confirm and give feedback in few hours.

**Comment by Remi-dee** [comment]
> > @Remi-dee does this work?
> 
> I’ll confirm and give feedback in few hours.

We can work with this

**Review by annonymousauthority — APPROVED** [review]

**Pull request merged**
